# vim:ft=kitty

## Cobalt2 Vibrant Kitty Diff

color_scheme auto

pygments_style default
dark_pygments_style monokai

# Basic colors
foreground      #193549
dark_foreground #FFFFFF
background      #FFFFFF
dark_background #193549

# Title colors
title_fg      #193549
dark_title_fg #FFFFFF
title_bg      #FFFFFF
dark_title_bg #193549

# Margin colors
margin_bg      #F0F4F8
dark_margin_bg #122738
margin_fg      #5C6B73
dark_margin_fg #80CBC4

# Removed text backgrounds
removed_bg                #FFD6DE
dark_removed_bg           #5A2638
highlight_removed_bg      #FF628C
dark_highlight_removed_bg #8F2D4A
removed_margin_bg         #FFB8C8
dark_removed_margin_bg    #FF628C

# Added text backgrounds
added_bg                #D8FFB8
dark_added_bg           #1F553A
highlight_added_bg      #8CFF5A
dark_highlight_added_bg #3AD900
added_margin_bg         #B9FF8A
dark_added_margin_bg    #3AD900

# Moved text backgrounds
moved_bg             #FFF3A3
dark_moved_bg        #075985
moved_margin_bg      #FFD92F
dark_moved_margin_bg #0088CC

# Filler
filler_bg      #F0F4F8
dark_filler_bg #1B4057

# Filler in margins
margin_filler_bg      none
dark_margin_filler_bg none

# Hunk header colors
hunk_margin_bg      #BFE9FF
dark_hunk_margin_bg #0066A1
hunk_bg             #D9F4FF
dark_hunk_bg        #075985

# Search / selection
search_bg      #FFC600
dark_search_bg #FFC600
search_fg      #193549
dark_search_fg #193549

select_bg      #0088CC
dark_select_bg #00A8FF
select_fg      #FFFFFF
dark_select_fg #FFFFFF
