# ============================================================
# THE EAGLE'S COBALT2 COLOR SCHEME
# ============================================================

# Core Colors
background            #193549
foreground            #ffffff
cursor                #f0cc09
selection_background  #0050a4
selection_foreground  #ffffff

# The ANSI Colors (For your terminal commands)
# Black
color0  #000000
color8  #666666

# Red
color1  #ff0000
color9  #ff0000

# Green
color2  #3ad900
color10 #3ad900

# Yellow (The iconic Cobalt2 Yellow! 🟡)
color3  #ffc600
color11 #ffc600

# Blue
color4  #0088ff
color12 #0088ff

# Magenta
color5  #ff2c70
color13 #ff2c70

# Cyan
color6  #00c5c7
color14 #00c5c7

# White
color7  #c7c7c7
color15 #feffff

# Tab Bar Colors
active_tab_foreground   #000
active_tab_background   #3ad900
active_tab_font_style   bold-italic
inactive_tab_foreground #444
inactive_tab_background #0088ff
inactive_tab_font_style normal
tab_bar_background      #193560

# KITTY Font
font_family JetBrainsMono Nerd Font Mono

# ============================================================
# GENERIC CONFIGURATIONS
# ============================================================
font_size 9.0
background_opacity 0.90
map_timeout 1.0

# ============================================================
# COPY PASTE CONFIGURATIONS
# ============================================================
map super+shift+c copy_last_command_output

# ============================================================
# SCROLL CONFIGURATIONS
# ============================================================
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

map alt+z scroll_to_prompt -1
map alt+x scroll_to_prompt 1

# ============================================================
# WINDOW CONFIGURATIONS
# ============================================================
remember_window_size no
window_padding_width 1

map alt+shift+l next_window
map alt+shift+h previous_window

map alt+enter new_window_with_cwd
map super+enter close_window

# ============================================================
# TAB CONFIGURATIONS
# ============================================================
active_tab_title_template "⚡{title}"
tab_bar_style slant
tab_fade 0.5 0.6 0.75 1

map alt+l next_tab
map alt+h previous_tab

map alt+t new_tab_with_cwd
map alt+w close_tab

map alt+shift+w set_tab_title

# ============================================================
# SESSIONS CONFIGURATIONS
# ============================================================
# Session Setttings
tab_bar_filter session:~
map f7>/ goto_session
map f7>s save_as_session --base-dir="$HOME/.local/share/kitty/sessions/"  --use-foreground-process
map f7>c close_session

# Session Files
map f7>1 goto_session /home/eagle/.local/share/kitty/sessions
