[[entry]]
played_at = "2026-08-23T07:41:33Z"
path = "/home/eagle/Music/Lyrical/Tumhe Apna Banane Ka.flac"
title = "Tumhe Apna Banane Ka"
artist = "Armaan Malik, Neeti Mohan"
album = "Hate Story 3"
genre = "Films/Games"
year = 2015
track_number = 1

[[entry]]
played_at = "2026-08-23T07:33:13Z"
path = "/home/eagle/Music/Lyrical/Tujhe Sochta Hoon.flac"
title = "Tujhe Sochta Hoon"
artist = "Pritam/ KK"
album = "Jannat 2 (Original Motion Picture Soundtrack)"
genre = "Films/Games"
year = 2012
track_number = 3

[[entry]]
played_at = "2026-08-21T20:33:11Z"
path = "/home/eagle/Music/Lyrical/Broken Angel (feat. Helena).flac"
title = "Broken Angel"
artist = "Arash/ Helena"
album = "Broken Angel (feat. Helena)"
genre = "Pop"
year = 2010
track_number = 1
