# ============================================================
# Autostart
# ============================================================

exec-once = qs -c noctalia-shell
exec-once = swww-daemon
exec = hyprshade on vibrance
exec-once = cliphist wipe
exec-once = wl-paste --type text --watch cliphist store
exec-once = /usr/lib/hyprpolkitagent/hyprpolkitagent
