# ============================================================
# Autostart
# ============================================================

exec-once = qs -c noctalia-shell
exec-once = awww-daemon
exec = hyprshade on vibrance

exec-once = cliphist list | grep -E '\[Binary data|image/' | cliphist delete
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
